### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ronnyroeller** [nalbion/linkedin-signin#1]
@nalbion - Thanks for open sourcing the element!
Could you please indicate the license of the project? I'd be happy to contribute to the project but would have to know if we can actually use it afterwards (e.g. license is Apache, MIT, or similar).

**Comment by nalbion** [comment]
Thanks for your interest. 
In the spirit of [Gustavo Isensee's linkedin-button](https://github.com/gustavoisensee/linkedin-button) I have updated the bower.json and README.md files to indicate the MIT licence.
